CREATE TABLE `employeeRequestLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestId` int NOT NULL,
	`action` varchar(100) NOT NULL,
	`oldStatus` varchar(50),
	`newStatus` varchar(50),
	`performedBy` int NOT NULL,
	`performedByName` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `employeeRequestLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `employeeRequests` (
	`id` int AUTO_INCREMENT NOT NULL,
	`requestNumber` varchar(50) NOT NULL,
	`employeeId` int NOT NULL,
	`employeeName` varchar(255) NOT NULL,
	`branchId` int,
	`branchName` varchar(255),
	`requestType` enum('advance','vacation','arrears','permission','objection','resignation') NOT NULL,
	`status` enum('pending','approved','rejected','cancelled') NOT NULL DEFAULT 'pending',
	`title` varchar(255) NOT NULL,
	`description` text,
	`advanceAmount` decimal(12,2),
	`advanceReason` text,
	`repaymentMethod` varchar(100),
	`vacationType` varchar(50),
	`vacationStartDate` timestamp,
	`vacationEndDate` timestamp,
	`vacationDays` int,
	`arrearsAmount` decimal(12,2),
	`arrearsPeriod` varchar(100),
	`arrearsDetails` text,
	`permissionDate` timestamp,
	`permissionStartTime` varchar(10),
	`permissionEndTime` varchar(10),
	`permissionHours` decimal(4,2),
	`permissionReason` text,
	`objectionType` varchar(100),
	`objectionDate` timestamp,
	`objectionDetails` text,
	`objectionEvidence` text,
	`resignationDate` timestamp,
	`resignationReason` text,
	`lastWorkingDay` timestamp,
	`noticePeriod` int,
	`reviewedBy` int,
	`reviewedByName` varchar(255),
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`rejectionReason` text,
	`priority` enum('low','normal','high','urgent') NOT NULL DEFAULT 'normal',
	`attachments` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employeeRequests_id` PRIMARY KEY(`id`),
	CONSTRAINT `employeeRequests_requestNumber_unique` UNIQUE(`requestNumber`)
);
