CREATE TABLE `employeeSalarySettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`baseSalary` decimal(12,2) NOT NULL DEFAULT '2000.00',
	`overtimeEnabled` boolean NOT NULL DEFAULT false,
	`overtimeRate` decimal(12,2) NOT NULL DEFAULT '1000.00',
	`isSupervisor` boolean NOT NULL DEFAULT false,
	`supervisorIncentive` decimal(12,2) NOT NULL DEFAULT '400.00',
	`fixedDeduction` decimal(12,2) NOT NULL DEFAULT '0.00',
	`fixedDeductionReason` text,
	`bankName` varchar(100),
	`bankAccount` varchar(50),
	`iban` varchar(50),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `employeeSalarySettings_id` PRIMARY KEY(`id`),
	CONSTRAINT `employeeSalarySettings_employeeId_unique` UNIQUE(`employeeId`)
);
--> statement-breakpoint
CREATE TABLE `expenseLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`expenseId` int NOT NULL,
	`action` varchar(100) NOT NULL,
	`oldStatus` varchar(50),
	`newStatus` varchar(50),
	`performedBy` int NOT NULL,
	`performedByName` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `expenseLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `expenses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`expenseNumber` varchar(50) NOT NULL,
	`category` enum('operational','administrative','marketing','maintenance','utilities','rent','salaries','supplies','transportation','other') NOT NULL,
	`title` varchar(255) NOT NULL,
	`description` text,
	`amount` decimal(15,2) NOT NULL,
	`branchId` int,
	`branchName` varchar(255),
	`expenseDate` timestamp NOT NULL,
	`paymentMethod` enum('cash','bank_transfer','check','credit_card','other') NOT NULL DEFAULT 'cash',
	`paymentReference` varchar(100),
	`supplierId` int,
	`supplierName` varchar(255),
	`attachments` text,
	`receiptNumber` varchar(100),
	`status` enum('pending','approved','rejected','paid') NOT NULL DEFAULT 'pending',
	`approvedBy` int,
	`approvedByName` varchar(255),
	`approvedAt` timestamp,
	`rejectionReason` text,
	`createdBy` int NOT NULL,
	`createdByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `expenses_id` PRIMARY KEY(`id`),
	CONSTRAINT `expenses_expenseNumber_unique` UNIQUE(`expenseNumber`)
);
--> statement-breakpoint
CREATE TABLE `payrollDetails` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payrollId` int NOT NULL,
	`employeeId` int NOT NULL,
	`employeeName` varchar(255) NOT NULL,
	`employeeCode` varchar(50) NOT NULL,
	`position` varchar(100),
	`baseSalary` decimal(12,2) NOT NULL DEFAULT '2000.00',
	`overtimeAmount` decimal(12,2) NOT NULL DEFAULT '0.00',
	`overtimeEnabled` boolean NOT NULL DEFAULT false,
	`incentiveAmount` decimal(12,2) NOT NULL DEFAULT '0.00',
	`isSupervisor` boolean NOT NULL DEFAULT false,
	`deductionAmount` decimal(12,2) NOT NULL DEFAULT '0.00',
	`deductionReason` text,
	`advanceDeduction` decimal(12,2) NOT NULL DEFAULT '0.00',
	`grossSalary` decimal(12,2) NOT NULL DEFAULT '0.00',
	`totalDeductions` decimal(12,2) NOT NULL DEFAULT '0.00',
	`netSalary` decimal(12,2) NOT NULL DEFAULT '0.00',
	`isPaid` boolean NOT NULL DEFAULT false,
	`paidAt` timestamp,
	`paymentMethod` varchar(50),
	`paymentReference` varchar(100),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payrollDetails_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payrolls` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payrollNumber` varchar(50) NOT NULL,
	`branchId` int NOT NULL,
	`branchName` varchar(255) NOT NULL,
	`year` int NOT NULL,
	`month` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`totalBaseSalary` decimal(15,2) NOT NULL DEFAULT '0.00',
	`totalOvertime` decimal(15,2) NOT NULL DEFAULT '0.00',
	`totalIncentives` decimal(15,2) NOT NULL DEFAULT '0.00',
	`totalDeductions` decimal(15,2) NOT NULL DEFAULT '0.00',
	`totalNetSalary` decimal(15,2) NOT NULL DEFAULT '0.00',
	`employeeCount` int NOT NULL DEFAULT 0,
	`status` enum('draft','pending','approved','paid','cancelled') NOT NULL DEFAULT 'draft',
	`approvedBy` int,
	`approvedByName` varchar(255),
	`approvedAt` timestamp,
	`paidAt` timestamp,
	`notes` text,
	`createdBy` int NOT NULL,
	`createdByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payrolls_id` PRIMARY KEY(`id`),
	CONSTRAINT `payrolls_payrollNumber_unique` UNIQUE(`payrollNumber`)
);
