CREATE TABLE `taskLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskId` int NOT NULL,
	`action` varchar(100) NOT NULL,
	`oldStatus` varchar(50),
	`newStatus` varchar(50),
	`performedBy` int,
	`performedByName` varchar(255),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `taskLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referenceNumber` varchar(6) NOT NULL,
	`subject` varchar(255) NOT NULL,
	`details` text,
	`requirement` text NOT NULL,
	`responseType` enum('file_upload','confirmation','text_response','multiple_files') NOT NULL DEFAULT 'file_upload',
	`confirmationYesText` varchar(255) DEFAULT 'نعم، قمت بذلك',
	`confirmationNoText` varchar(255) DEFAULT 'لا، لم أقم بذلك حتى الآن',
	`branchId` int,
	`branchName` varchar(255),
	`assignedToId` int NOT NULL,
	`assignedToName` varchar(255) NOT NULL,
	`assignedToEmail` varchar(320),
	`status` enum('pending','in_progress','completed','cancelled') NOT NULL DEFAULT 'pending',
	`responseText` text,
	`responseConfirmation` boolean,
	`responseFiles` text,
	`respondedAt` timestamp,
	`dueDate` timestamp,
	`priority` enum('low','medium','high','urgent') NOT NULL DEFAULT 'medium',
	`createdBy` int NOT NULL,
	`createdByName` varchar(255),
	`emailSent` boolean NOT NULL DEFAULT false,
	`emailSentAt` timestamp,
	`reminderSent` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tasks_id` PRIMARY KEY(`id`),
	CONSTRAINT `tasks_referenceNumber_unique` UNIQUE(`referenceNumber`)
);
