CREATE TABLE `aiAdvancedRecommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`recommendationType` enum('cost_reduction','revenue_increase','efficiency_improvement','risk_mitigation','staffing_optimization','process_automation','pricing_adjustment','inventory_optimization') NOT NULL,
	`priority` enum('low','medium','high','critical') NOT NULL DEFAULT 'medium',
	`title` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`descriptionAr` text NOT NULL,
	`branchId` int,
	`expectedImpact` json,
	`actionSteps` json,
	`confidenceScore` decimal(5,2) NOT NULL,
	`status` enum('new','under_review','approved','in_progress','completed','rejected','deferred') NOT NULL DEFAULT 'new',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`implementedBy` int,
	`implementedAt` timestamp,
	`actualImpact` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `aiAdvancedRecommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `aiPredictions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`predictionType` enum('revenue_forecast','expense_forecast','profit_forecast','demand_forecast','staffing_needs','cash_flow_forecast') NOT NULL,
	`targetPeriod` enum('day','week','month','quarter') NOT NULL,
	`targetDate` timestamp NOT NULL,
	`branchId` int,
	`branchName` varchar(255),
	`predictedValue` decimal(15,2) NOT NULL,
	`confidenceLevel` decimal(5,2) NOT NULL,
	`lowerBound` decimal(15,2),
	`upperBound` decimal(15,2),
	`actualValue` decimal(15,2),
	`accuracy` decimal(5,2),
	`factors` json,
	`modelVersion` varchar(50),
	`modelParams` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `aiPredictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `auditEvents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`userName` varchar(200),
	`userRole` varchar(50),
	`userBranchId` int,
	`eventType` enum('create','update','delete','view','export','import','login','logout','login_failed','password_change','approval','rejection','payment','transfer','config_change','permission_change','bulk_operation') NOT NULL,
	`entityType` varchar(100) NOT NULL,
	`entityId` int,
	`entityName` varchar(255),
	`oldData` json,
	`newData` json,
	`changedFields` json,
	`description` text,
	`ipAddress` varchar(50),
	`userAgent` text,
	`sessionId` varchar(100),
	`riskLevel` enum('low','medium','high','critical') NOT NULL DEFAULT 'low',
	`isAnomaly` boolean NOT NULL DEFAULT false,
	`anomalyScore` decimal(5,2),
	`anomalyReason` text,
	`reviewStatus` enum('pending','reviewed','flagged','resolved') DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `auditEvents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `complianceRules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`code` varchar(50) NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameAr` varchar(255) NOT NULL,
	`description` text,
	`category` enum('financial','hr','operational','security','data_privacy') NOT NULL,
	`conditions` json,
	`severity` enum('info','warning','violation','critical') NOT NULL DEFAULT 'warning',
	`autoAction` enum('none','notify','block','escalate') DEFAULT 'notify',
	`notifyRoles` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdBy` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `complianceRules_id` PRIMARY KEY(`id`),
	CONSTRAINT `complianceRules_code_unique` UNIQUE(`code`)
);
--> statement-breakpoint
CREATE TABLE `complianceViolations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ruleId` int NOT NULL,
	`ruleCode` varchar(50) NOT NULL,
	`ruleName` varchar(255) NOT NULL,
	`violationType` enum('threshold_exceeded','unauthorized_access','policy_breach','data_anomaly','timing_violation','approval_bypass') NOT NULL,
	`severity` enum('info','warning','violation','critical') NOT NULL,
	`entityType` varchar(100) NOT NULL,
	`entityId` int,
	`entityName` varchar(255),
	`userId` int,
	`userName` varchar(200),
	`branchId` int,
	`description` text NOT NULL,
	`evidence` json,
	`status` enum('open','investigating','resolved','dismissed','escalated') NOT NULL DEFAULT 'open',
	`assignedTo` int,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`resolution` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `complianceViolations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `executiveAlerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alertType` enum('revenue_drop','expense_spike','profit_warning','cash_flow_risk','compliance_issue','performance_alert','document_expiry','target_achievement','anomaly_detected') NOT NULL,
	`severity` enum('info','warning','critical') NOT NULL DEFAULT 'warning',
	`title` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`message` text NOT NULL,
	`messageAr` text NOT NULL,
	`entityType` varchar(100),
	`entityId` int,
	`branchId` int,
	`metrics` json,
	`recommendation` text,
	`recommendationAr` text,
	`status` enum('active','acknowledged','resolved','dismissed') NOT NULL DEFAULT 'active',
	`acknowledgedBy` int,
	`acknowledgedAt` timestamp,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`notificationSent` boolean NOT NULL DEFAULT false,
	`notificationSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `executiveAlerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `kpiSnapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`snapshotDate` timestamp NOT NULL,
	`periodType` enum('daily','weekly','monthly','quarterly','yearly') NOT NULL,
	`year` int NOT NULL,
	`month` int,
	`week` int,
	`day` int,
	`branchId` int,
	`branchName` varchar(255),
	`totalRevenue` decimal(15,2) NOT NULL DEFAULT '0',
	`cashRevenue` decimal(15,2) NOT NULL DEFAULT '0',
	`networkRevenue` decimal(15,2) NOT NULL DEFAULT '0',
	`totalExpenses` decimal(15,2) NOT NULL DEFAULT '0',
	`operationalExpenses` decimal(15,2) NOT NULL DEFAULT '0',
	`salaryExpenses` decimal(15,2) NOT NULL DEFAULT '0',
	`netProfit` decimal(15,2) NOT NULL DEFAULT '0',
	`profitMargin` decimal(5,2) NOT NULL DEFAULT '0',
	`totalEmployees` int NOT NULL DEFAULT 0,
	`activeEmployees` int NOT NULL DEFAULT 0,
	`attendanceRate` decimal(5,2) DEFAULT '0',
	`pendingRequests` int DEFAULT 0,
	`expiringDocuments` int DEFAULT 0,
	`totalTransactions` int DEFAULT 0,
	`averageTransactionValue` decimal(12,2) DEFAULT '0',
	`revenueGrowth` decimal(5,2),
	`expenseGrowth` decimal(5,2),
	`profitGrowth` decimal(5,2),
	`additionalMetrics` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `kpiSnapshots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `riskAlerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`riskType` enum('financial','operational','compliance','hr','market','liquidity') NOT NULL,
	`riskLevel` enum('low','medium','high','critical') NOT NULL,
	`riskScore` decimal(5,2) NOT NULL,
	`title` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`description` text NOT NULL,
	`descriptionAr` text NOT NULL,
	`branchId` int,
	`indicators` json,
	`potentialImpact` json,
	`mitigationPlan` json,
	`status` enum('active','monitoring','mitigating','resolved','accepted') NOT NULL DEFAULT 'active',
	`assignedTo` int,
	`resolvedBy` int,
	`resolvedAt` timestamp,
	`resolution` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `riskAlerts_id` PRIMARY KEY(`id`)
);
