CREATE TABLE `documentAlertLogs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`employeeId` int NOT NULL,
	`employeeName` varchar(255) NOT NULL,
	`employeeCode` varchar(50),
	`branchId` int,
	`branchName` varchar(255),
	`documentType` enum('iqama','health_cert','contract') NOT NULL,
	`expiryDate` date NOT NULL,
	`daysRemaining` int NOT NULL,
	`alertType` enum('auto','manual') NOT NULL DEFAULT 'auto',
	`channel` enum('email','sms','both','in_app') NOT NULL,
	`status` enum('sent','failed','pending') NOT NULL DEFAULT 'pending',
	`sentAt` timestamp,
	`recipientEmail` varchar(320),
	`recipientPhone` varchar(20),
	`recipientCount` int NOT NULL DEFAULT 1,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `documentAlertLogs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `documentAlertSettings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`documentType` enum('iqama','health_cert','contract') NOT NULL,
	`nameAr` varchar(100) NOT NULL,
	`isEnabled` boolean NOT NULL DEFAULT true,
	`alertDays` json NOT NULL,
	`sendEmail` boolean NOT NULL DEFAULT true,
	`sendSms` boolean NOT NULL DEFAULT false,
	`sendInApp` boolean NOT NULL DEFAULT true,
	`sendHour` int NOT NULL DEFAULT 8,
	`notifyAdmin` boolean NOT NULL DEFAULT true,
	`notifyGeneralSupervisor` boolean NOT NULL DEFAULT true,
	`notifyBranchSupervisor` boolean NOT NULL DEFAULT true,
	`notifyEmployee` boolean NOT NULL DEFAULT false,
	`customMessage` text,
	`updatedBy` int,
	`updatedByName` varchar(255),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `documentAlertSettings_id` PRIMARY KEY(`id`)
);
