CREATE TABLE `ocr_audit_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`branchId` int NOT NULL,
	`userId` varchar(64) NOT NULL,
	`revenueDate` varchar(10) NOT NULL,
	`imageUrl` text,
	`inputNetworkAmount` decimal(12,2),
	`inputDate` varchar(10) NOT NULL,
	`extractedAmount` decimal(12,2),
	`extractedDate` varchar(10),
	`extractedSections` json,
	`status` enum('success','amount_mismatch','date_mismatch','both_mismatch','low_confidence','extraction_failed','no_image','error') NOT NULL,
	`confidence` enum('high','medium','low','none') NOT NULL,
	`isAmountMatched` boolean DEFAULT false,
	`isDateMatched` boolean DEFAULT false,
	`amountDifference` decimal(12,2),
	`processingTimeMs` int,
	`errorMessage` text,
	`warnings` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ocr_audit_logs_id` PRIMARY KEY(`id`)
);
